----
title : "STA 141A Project Question 4"
author : "Jay Bendre, John Dinh, Grant Gambetta and Ignat Kulinka"
output: 'html_document'
----

```{r message = FALSE, warning = FALSE}
# Importing all the libraries required
library(ggplot2)
library(ipumsr)
library(dplyr)
library(splitstackshape)
library(caret)
library(glmnet)
library(MASS)
library(imbalance)
```

```{r}
# Loading the data and creating a dataframe
df_ddi <- read_ipums_ddi("nhis_00001.xml")
df <- as.data.frame(read_ipums_micro(df_ddi, verbose = FALSE))
head(df)
```

```{r}
df$USUALPL
```


### Question 3
#### random forest
```{r}
cvd_test_df <- df %>% dplyr::filter(CVDTEST == 1 | CVDTEST == 2) # select only yes or no for covid test variable
cvd_test_df$CVDTEST  <- ifelse(cvd_test_df$CVDTEST == 1, 0, 1) # relevel covid test variable: # 0 = no test, 1 = test
barplot(table(cvd_test_df$CVDTEST))
```

```{r}
table(df$CVDDIAG)/length(df$CVDDIAG)
```

```{r}
cvd_test_df <- cvd_test_df %>% dplyr::select(NHISHID, SEX, AGE, FAMSIZE, EMPSTAT, HOURSWRK, PAIDSICK, EMPHI, EMPFT, USUALPL, HINOTCOVE, INCFAM07ON, FAMTOTINC, CVDTEST)
# re factor variables, 7 = unknown
cvd_test_df$PAIDSICK[cvd_test_df$PAIDSICK == 8] = 7
cvd_test_df$PAIDSICK[cvd_test_df$PAIDSICK == 9] = 7
cvd_test_df$EMPHI[cvd_test_df$EMPHI == 8] = 7
cvd_test_df$EMPHI[cvd_test_df$EMPHI == 9] = 7
cvd_test_df$EMPFT[cvd_test_df$EMPFT == 8] = 7
cvd_test_df$EMPFT[cvd_test_df$EMPFT == 9] = 7
cvd_test_df$USUALPL[cvd_test_df$USUALPL == 8] = 7
cvd_test_df$USUALPL[cvd_test_df$USUALPL == 9] = 7
cvd_test_df$HOURSWRK <- as.double(cvd_test_df$HOURSWRK)
cvd_test_df <- cvd_test_df %>% mutate_if(is.integer, as.factor)
cvd_test_df
```

### logistic regression

```{r}
# oversample the data
set.seed(123)
vec <- c(3000, 2000)
names(vec) <- c(0, 1)
strat_sample <- stratified(cvd_test_df, group = 'CVDTEST', size = vec)
strat_sample

table(strat_sample$CVDTEST)/length(strat_sample$CVDTEST)
barplot(table(strat_sample$CVDTEST))
```


```{r}
set.seed(123)
lr_train <- strat_sample %>% dplyr::sample_frac(0.70)
lr_test <- dplyr::anti_join(strat_sample, lr_train, by = "NHISHID")
lr_train <- lr_train %>% dplyr::select(-c("NHISHID"))
lr_test <- lr_test %>% dplyr::select(-c("NHISHID"))

lr2 <- glm(data = lr_train, CVDTEST ~ ., family = 'binomial')
summary(lr2)
```



```{r}
null_model <- glm(data = lr_train, CVDTEST ~ 1, family = 'binomial')
full_model <- glm(data = lr_train, CVDTEST ~ ., family = 'binomial')
step <- stepAIC(null_model, scope = list(lower = ~1, upper = full_model), direction = 'both', k = 2, trace = 0)
step$anova
```


```{r}
# final model
lr2 <- glm(data = lr_train, CVDTEST ~ EMPSTAT + HINOTCOVE + AGE + USUALPL + FAMTOTINC, family = 'binomial')
summary(lr2)
lr2_probs <- predict(lr2, newdata = lr_test, type = 'response')
lr2_predicted <- ifelse(lr2_probs < 0.5, 0, 1)

confusionMatrix(factor(lr2_predicted, levels=min(lr_test$CVDTEST):max(lr_test$CVDTEST)), factor(lr_test$CVDTEST, levels=min(lr_test$CVDTEST):max(lr_test$CVDTEST)))
```


```{r}
library(stargazer)

stargazer(lr2)
```


